### ISSUE TITLE
Runing SynthSR on Mac(M1)

### ISSUE THREAD

**Issue by sw3866** [BBillot/SynthSR#14]
Hello SynthSR team,

I am trying to run SynthSR on a Macbook Air (M1) using the development version of Freesurfer (freesurfer-macOS-darwin_arm64-dev.pkg).I'm using brain1.nii.gz (located in SynthSR's date folder) as my input, but the output shows there are two errors about the input dimensions. Do I have to convert the input dimensions to 4D in order to run it on my laptop? What method should I use to do the conversion (e.g. tensorflow or something else)?

Errors:

2 root error(s) found.
  (0) INVALID_ARGUMENT:  input must be 4-dimensional[1,160,192,160,24]
	 [[{{node unet/unet_bn_down_0/FusedBatchNormV3}}]]
	 [[unet/unet_conv_downarm_2_0/BiasAdd/_38]]
  (1) INVALID_ARGUMENT:  input must be 4-dimensional[1,160,192,160,24]
	 [[{{node unet/unet_bn_down_0/FusedBatchNormV3}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_predict_function_1938]

<img width="568" alt="Screenshot 2024-02-16 at 3 32 59 PM" src="https://github.com/BBillot/SynthSR/assets/144161905/663b5820-6be1-41d1-8e59-5d45dda49f5a">
[Runing SynthSR on Mac.txt](https://github.com/BBillot/SynthSR/files/14315820/Runing.SynthSR.on.Mac.txt)

Best,
Siyan Wen

**Comment by BBillot** [comment]
Hi, thanks for the interest in our tool.

just to be clear, this error is not due to SynthSR in particular, but to mac/tensorflow/GPU compatibility issues.
Please have a look at the answer provided by a member of our community for another one of our tool (SynthSeg).
https://github.com/BBillot/SynthSeg/issues/81#issuecomment-1947505992

A temporary solution is to force running the code on the cpu by using the `--cpu` flag. 
The rest of the issue is independent to SynthSR, and will have to be solved externally (i.e., tensorflow support).

Hope this helps,
Benjamin
