### ISSUE TITLE
Overestimation in SynthSR

### ISSUE THREAD

**Issue by loneblues** [BBillot/SynthSR#7]
![image](https://user-images.githubusercontent.com/21212266/224295080-072e1133-7699-493b-a965-8b3442513dbb.png)
![image](https://user-images.githubusercontent.com/21212266/224295104-c90a60f0-6771-4f24-8205-5274681ba0ff.png)

Hi! Thanks for the amazing software. 
I've been trying to apply this to a ct data, however there appears to be some significant over-estimation in this process. 
Hope you can suggest a way to handle this issue. 
Also, this happens regardless (actually looks exactly the same) of skull stripping. 

Thanks in advance.

**Comment by BBillot** [comment]
Hello and thanks for the interest in our tool!

SynthSR is trained with images that have a skull. Therefore, it will always try to synthesise a skull in the output. But if you want to remove the skull in the output of SynthSR, you can mask them with the mask of the input (ie where the input image is not zero).

Hope this helps,
The authors

**Comment by loneblues** [comment]
Hi. 

Thanks for your kind reply and congratulations on your recent articles published in prestigeous journals. 

I think I wasn't clear enough about the situtation. 
What I meant by overestimation is the right hippocampus, which appears significantly larger than the original CT, visually and obviously the volume or automated atrophy score derived from it all overestimates the volume of the hippocampus. 
I posted a capture of a skull-stripped image, but this happens quite consistently regardless of the skull being present or not. 
Sorry for not being more clearer in the first post. 

Thanks in advance for your answer.

**Comment by BBillot** [comment]
Hi, sorry for the late answer. 
Thanks for the clarification. I think estimating the volume of the hippocampus from the CT is a bit hard, especially because of the high noise, very low tissue contrast, and generally low resolution. Therefore, direct comparison between CT and SynthSR's output can be misleading. But of course, SynthSR can sometimes produce bad results, and this is true for CT scans, which are particularly hard for the reasons mentioned above. Unfortunately, I don't have any trick to obtain better results, expect to use the --ct flag and to process non skull-stripped data.
Best
Benjamin
